### ISSUE TITLE
 from tieba.caches.location import DATABASE_USER_NAME, DATABASE_PASSWORD ImportError: No module named caches.location

### ISSUE THREAD

**Issue by a89169** [changleibox/TiebaCrawler#2]
您好，我导入后缺少tieba.caches.location这个模块，请问是什么原因呢，谢谢！
@a89169 您好：
tieba.caches.location这个模块是存放自己数据库的用户名和密码，请自己创建这个模块，添加下面两个字段儿：
`DATABASE_USER_NAME = '用户名'
DATABASE_PASSWORD = '密码'`

**Comment by changleibox** [comment]
tieba.caches.location这个模块是存放自己数据库的用户名和密码，请自己创建这个模块，添加下面两个字段儿：

**Comment by changleibox** [comment]
DATABASE_USER_NAME = '用户名'
DATABASE_PASSWORD = '密码'

**Comment by a89169** [comment]
好的，非常感谢！
