### ISSUE TITLE
i am lilei

### ISSUE THREAD

**Issue by kyiln** [changleibox/TiebaCrawler#3]
我是一名java工程师，有兴趣聊聊吗

**Comment by kyiln** [comment]
我的练习qq：130808991 
微信：kylin19910808

**Comment by changleibox** [comment]
> 我的练习qq：130808991
> 微信：kylin19910808

你是有啥问题吗

**Comment by kyiln** [comment]
加qq或微信说嘛。我最近在研究自动化发帖回复方面的。准备弄个软件。想和你谈谈。反正都在成都嘛。正好都有一个雷字 哈哈





------------------ Original ------------------
